/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package gui;

import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class AddSupplier extends javax.swing.JDialog {

    /** Creates new form customer */
    public AddSupplier(String supplierNo, String supplierName, String supplierAddress, String roadName) {
        initComponents();

        jTextField4.setText(supplierNo);
        jTextField6.setText(supplierName);
        jTextArea1.setText(supplierAddress);
        jTextField5.setText(roadName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(975, 856));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(975, 856));
        jPanel1.setPreferredSize(new java.awt.Dimension(975, 856));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 25));
        jPanel21.setToolTipText("");
        jPanel21.setMaximumSize(new java.awt.Dimension(32767, 64));
        jPanel21.setMinimumSize(new java.awt.Dimension(975, 57));
        jPanel21.setPreferredSize(new java.awt.Dimension(975, 57));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("FMEmanee", 0, 35)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(73, 80, 87));
        jLabel15.setText("kj iemhqïlrejka");
        jPanel21.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, -1));

        jPanel1.add(jPanel21, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(975, 792));
        jPanel2.setPreferredSize(new java.awt.Dimension(975, 792));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 1, 46, new java.awt.Color(255, 255, 255)));
        jPanel3.setMinimumSize(new java.awt.Dimension(975, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(975, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("FMMalithi", 0, 31)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(15, 15, 18));
        jLabel19.setText("iemhqïlref.a wxlh");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(255, 255, 255)));
        jLabel19.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jLabel19.setMinimumSize(new java.awt.Dimension(296, 40));
        jLabel19.setPreferredSize(new java.awt.Dimension(296, 40));
        jLabel19.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel19, java.awt.BorderLayout.PAGE_START);

        jTextField4.setBackground(new java.awt.Color(245, 245, 245));
        jTextField4.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(15, 15, 18));
        jTextField4.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        jTextField4.setMinimumSize(new java.awt.Dimension(882, 55));
        jTextField4.setPreferredSize(new java.awt.Dimension(882, 55));
        jPanel3.add(jTextField4, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 1, 46, new java.awt.Color(255, 255, 255)));
        jPanel5.setMinimumSize(new java.awt.Dimension(975, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(975, 100));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("FMMalithi", 0, 31)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(15, 15, 18));
        jLabel21.setText("iemhqïlref.a ku");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(255, 255, 255)));
        jLabel21.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jLabel21.setMinimumSize(new java.awt.Dimension(296, 40));
        jLabel21.setPreferredSize(new java.awt.Dimension(296, 40));
        jLabel21.setVerifyInputWhenFocusTarget(false);
        jPanel5.add(jLabel21, java.awt.BorderLayout.PAGE_START);

        jTextField6.setBackground(new java.awt.Color(245, 245, 245));
        jTextField6.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(15, 15, 18));
        jTextField6.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        jTextField6.setMinimumSize(new java.awt.Dimension(882, 55));
        jTextField6.setPreferredSize(new java.awt.Dimension(882, 55));
        jPanel5.add(jTextField6, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 1, 46, new java.awt.Color(255, 255, 255)));
        jPanel4.setMinimumSize(new java.awt.Dimension(975, 191));
        jPanel4.setPreferredSize(new java.awt.Dimension(975, 191));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("FMMalithi", 0, 31)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(15, 15, 18));
        jLabel20.setText("iemhqïlref.a ,smskh");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(255, 255, 255)));
        jLabel20.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jLabel20.setMinimumSize(new java.awt.Dimension(296, 40));
        jLabel20.setPreferredSize(new java.awt.Dimension(296, 40));
        jLabel20.setVerifyInputWhenFocusTarget(false);
        jPanel4.add(jLabel20, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(882, 140));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(882, 140));

        jTextArea1.setBackground(new java.awt.Color(245, 245, 245));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(15, 15, 18));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setMinimumSize(new java.awt.Dimension(875, 135));
        jTextArea1.setPreferredSize(new java.awt.Dimension(875, 135));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 1, 46, new java.awt.Color(255, 255, 255)));
        jPanel6.setMinimumSize(new java.awt.Dimension(975, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(975, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("FMMalithi", 0, 31)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(15, 15, 18));
        jLabel22.setText("ud¾.fha ku ");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(255, 255, 255)));
        jLabel22.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jLabel22.setMinimumSize(new java.awt.Dimension(296, 40));
        jLabel22.setPreferredSize(new java.awt.Dimension(296, 40));
        jLabel22.setVerifyInputWhenFocusTarget(false);
        jPanel6.add(jLabel22, java.awt.BorderLayout.PAGE_START);

        jTextField5.setBackground(new java.awt.Color(245, 245, 245));
        jTextField5.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(15, 15, 18));
        jTextField5.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        jTextField5.setMinimumSize(new java.awt.Dimension(882, 55));
        jTextField5.setPreferredSize(new java.awt.Dimension(882, 55));
        jPanel6.add(jTextField5, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 1, 46, new java.awt.Color(255, 255, 255)));
        jPanel7.setMinimumSize(new java.awt.Dimension(975, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(975, 100));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("FMMalithi", 0, 31)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(15, 15, 18));
        jLabel23.setText("m%jdyk wkqmd;h");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 10, 1, new java.awt.Color(255, 255, 255)));
        jLabel23.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        jLabel23.setMinimumSize(new java.awt.Dimension(296, 40));
        jLabel23.setPreferredSize(new java.awt.Dimension(296, 40));
        jLabel23.setVerifyInputWhenFocusTarget(false);
        jPanel7.add(jLabel23, java.awt.BorderLayout.PAGE_START);

        jTextField7.setBackground(new java.awt.Color(245, 245, 245));
        jTextField7.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(15, 15, 18));
        jTextField7.setMaximumSize(new java.awt.Dimension(2147483647, 52));
        jTextField7.setMinimumSize(new java.awt.Dimension(882, 55));
        jTextField7.setPreferredSize(new java.awt.Dimension(882, 55));
        jPanel7.add(jTextField7, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel7);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 46, 20, 46, new java.awt.Color(255, 255, 255)));
        jPanel28.setMinimumSize(new java.awt.Dimension(975, 72));
        jPanel28.setPreferredSize(new java.awt.Dimension(975, 72));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setMaximumSize(new java.awt.Dimension(400, 77));
        jPanel32.setMinimumSize(new java.awt.Dimension(400, 77));
        jPanel32.setPreferredSize(new java.awt.Dimension(400, 77));
        jPanel32.setLayout(new java.awt.BorderLayout(15, 0));

        jButton15.setBackground(new java.awt.Color(57, 117, 104));
        jButton15.setFont(new java.awt.Font("FMMalithi", 0, 22)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        jButton15.setText("iqrlskak");
        jButton15.setIconTextGap(8);
        jButton15.setMargin(new java.awt.Insets(2, 9, 2, 9));
        jButton15.setMaximumSize(new java.awt.Dimension(135, 52));
        jButton15.setMinimumSize(new java.awt.Dimension(135, 52));
        jButton15.setOpaque(true);
        jButton15.setPreferredSize(new java.awt.Dimension(135, 52));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton15, java.awt.BorderLayout.CENTER);

        jButton16.setBackground(new java.awt.Color(30, 39, 46));
        jButton16.setFont(new java.awt.Font("FMMalithi", 0, 22)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        jButton16.setText("bj;a jkak");
        jButton16.setIconTextGap(8);
        jButton16.setMargin(new java.awt.Insets(2, 9, 2, 9));
        jButton16.setMaximumSize(new java.awt.Dimension(175, 52));
        jButton16.setMinimumSize(new java.awt.Dimension(175, 52));
        jButton16.setOpaque(true);
        jButton16.setPreferredSize(new java.awt.Dimension(175, 52));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton16, java.awt.BorderLayout.LINE_END);

        jButton18.setBackground(new java.awt.Color(68, 150, 207));
        jButton18.setFont(new java.awt.Font("FMMalithi", 0, 22)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loading.png"))); // NOI18N
        jButton18.setIconTextGap(8);
        jButton18.setMargin(new java.awt.Insets(2, 9, 2, 9));
        jButton18.setMaximumSize(new java.awt.Dimension(55, 52));
        jButton18.setMinimumSize(new java.awt.Dimension(55, 52));
        jButton18.setOpaque(true);
        jButton18.setPreferredSize(new java.awt.Dimension(55, 52));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel32.add(jButton18, java.awt.BorderLayout.LINE_START);

        jPanel28.add(jPanel32, java.awt.BorderLayout.LINE_END);

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setMinimumSize(new java.awt.Dimension(50, 52));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel28.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel28);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:

        /*String yearString = String.valueOf(jComboBox2.getSelectedItem());
        String month = String.valueOf(jComboBox1.getSelectedItem());
        String rate = jTextField1.getText().trim();

        if (yearString.equals("අවුරුද්ද") || yearString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "wjqreoao f;darkak", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (month.equals("මාසය") || month.isEmpty()) {
            JOptionPane.showMessageDialog(this, "udih f;darkak", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (rate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "o¿ ñ< we;=,;a lrkak", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // Validate if rate is a valid number (either integer or float)
                Float.parseFloat(rate); // Attempt to parse rate as a float

                // Convert yearString to Year object
                Year year = Year.parse(yearString);

                // First check if the ID already exists

                if ("iqrlskak".equals(jButton15.getText())) {
                    try {

                        LeafService leafService = new LeafService();
                        int fleaf = leafService.findByData(yearString, month, rate);

                        if (fleaf > 0) {
                            // ID exists, show error message
                            JOptionPane.showMessageDialog(this, "fuu o;a;h oekgu;a mj;S' lreKdlr fjk;a o;a;h we;=,;a lrkak'", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {

                            // Create a Transport object and set the values
                            Leaf leaf = new Leaf();
                            leaf.setYear(year);
                            leaf.setMonth(month);
                            leaf.setLeaf_rate(rate);

                            // Call the save method in transportService
                            leafService.save(leaf);
                            String searchText = jTextField2.getText();
                            if(searchText.equals("ටයිප් කරන්න...")){
                                loadTable();
                            } else{
                                searchTable(searchText);
                            }
                            clear();

                        }

                    } catch (Exception e) {
                        logger.log(Level.WARNING, "LeafRate", e);
                        e.printStackTrace();

                    }
                } else {

                    int row = jTable.getSelectedRow();

                    if (row != -1) {  // Ensure a row is selected

                        try {
                            // Retrieve the ID from the selected row
                            String id = (String) jTable.getValueAt(row, 0);  // Assuming 'Id' is in the first column (index 0)

                            // Create a Leaf object and set the values
                            Leaf leaf = new Leaf();
                            leaf.setId(id);  // Set the selected Id
                            leaf.setYear(year);  // Set the selected year
                            leaf.setMonth(month);  // Set the selected month
                            leaf.setLeaf_rate(rate);  // Set the leaf rate

                            // Call the update method in leafService
                            LeafService leafService = new LeafService();
                            boolean response = leafService.update(leaf);

                            if(!response){
                                JOptionPane.showMessageDialog(this, "fuu o;a;h oekgu;a mj;S' lreKdlr fjk;a o;a;h we;=,;a lrkak'", "Error", JOptionPane.ERROR_MESSAGE);
                                return;
                            }

                        } catch (Exception e) {
                            // Log the error
                            e.printStackTrace();
                            logger.log(Level.WARNING, "LeafRate", e);
                        }

                        clear();

                        // Unselect the row if any was selected
                        jTable.clearSelection();
                        String searchText = jTextField2.getText();
                        if(searchText.equals("ටයිප් කරන්න...")){
                            loadTable();
                        } else{
                            searchTable(searchText);
                        }

                        setSaveButton();
                    }
                }

            } catch (NumberFormatException e) {
                // If the rate is not a valid number, show an error message
                JOptionPane.showMessageDialog(this, "lreKdlr o¿ ñ< wxlhla f,i we;=,;a lrkak'", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }*/
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        this.dispose();
       
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        /*int row = jTable.getSelectedRow();
        clear();
        if (row != -1) {
            // Unselect the row
            jTable.clearSelection();
        }
        loadTable();
        jTextField2.setText("ටයිප් කරන්න...");
        setSaveButton();*/
    }//GEN-LAST:event_jButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSupplier dialog = new AddSupplier("", "", "", "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

}
