/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author ECOTEC
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        // Inside initComponents() method, find and replace the jPanel6 initialization
        // Replace jPanel6 with your custom panel
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel()
        ;
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setPreferredSize(new java.awt.Dimension(1280, 1024));

        jPanel1.setMinimumSize(new java.awt.Dimension(269, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(269, 1024));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 126));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(269, 126));
        jPanel2.setLayout(new java.awt.GridLayout());

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("FMEmanee", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 80, 87));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        jLabel1.setText("ì,am;a moaO;sh");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        jLabel1.setIconTextGap(5);
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 898));
        jPanel4.setPreferredSize(new java.awt.Dimension(269, 898));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 256));
        jPanel5.setPreferredSize(new java.awt.Dimension(269, 256));
        jPanel5.setLayout(new java.awt.GridLayout(4, 1));

        jPanel6.setBackground(new java.awt.Color(236, 243, 242));
        jPanel6.setForeground(new java.awt.Color(236, 243, 242));
        jPanel6.setMinimumSize(new java.awt.Dimension(100, 64));
        jPanel6.setPreferredSize(new java.awt.Dimension(269, 64));
        jPanel6.setVerifyInputWhenFocusTarget(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 102, 204));
        jLabel3.setFont(new java.awt.Font("FMMalithi", 1, 27)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 117, 104));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/master_i.png"))); // NOI18N
        jLabel3.setText("ieliqï");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jLabel3.setDoubleBuffered(true);
        jLabel3.setIconTextGap(8);
        jLabel3.setMaximumSize(new java.awt.Dimension(170, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(170, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 30));
        jPanel6.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("FMMalithi", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 117, 104));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/down_ar.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        jPanel6.add(jLabel2, java.awt.BorderLayout.LINE_END);

        jPanel5.add(jPanel6);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("FMMalithi", 1, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(147, 159, 171));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle.png"))); // NOI18N
        jButton1.setText("m%jdyk wkqmd;h ");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 1, 1));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(10);
        jButton1.setInheritsPopupMenu(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("FMMalithi", 1, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(147, 159, 171));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle.png"))); // NOI18N
        jButton2.setText("iemhqïlrejka");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 1, 1));
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(10);
        jButton2.setInheritsPopupMenu(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("FMMalithi", 1, 25)); // NOI18N
        jButton3.setForeground(new java.awt.Color(147, 159, 171));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/circle.png"))); // NOI18N
        jButton3.setText("o¿ ñ<");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 35, 1, 1));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(10);
        jButton3.setInheritsPopupMenu(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel8.setMinimumSize(new java.awt.Dimension(100, 322));
        jPanel8.setPreferredSize(new java.awt.Dimension(269, 322));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jPanel9.setMinimumSize(new java.awt.Dimension(100, 192));
        jPanel9.setPreferredSize(new java.awt.Dimension(269, 192));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        jPanel10.setMinimumSize(new java.awt.Dimension(100, 128));
        jPanel10.setPreferredSize(new java.awt.Dimension(269, 128));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, -1, -1));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Change the text and icon of jButton3 when jButton1 is clicked
    jButton1.setIcon(new ImageIcon(getClass().getResource("/img/fill_circle.png")));
    jButton2.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
    jButton3.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
    jPanel6.setBackground(new Color(236, 243, 242)); // Example color: light red
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/img/fill_circle.png")));
    jButton3.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
    jPanel6.setBackground(new Color(255, 255, 255)); // Example color: light red
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton1.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
    jButton3.setIcon(new ImageIcon(getClass().getResource("/img/fill_circle.png")));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();

        int radius = 15;

        UIManager.put("Button.arc", radius);
        UIManager.put("Component.arc", radius);
        UIManager.put("TextComponent.arc", radius);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    new Home().setVisible(true);
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
